### ISSUE TITLE
Login credentials lost after app is killed

### ISSUE THREAD

**Issue by josuah** [brilliantlabsAR/noa-flutter#102]
The bug was encountered on iOS (private message on Discord):

The Google credential do not seem to be persistent across application restart, and need to be entered again every new launch of the app, possibly after the application was swiped away from the list of recent apps.

**Comment by siliconwitch** [comment]
Sounds like a bug. Will test this. What iPhone do they use?

**Comment by josuah** [comment]
I could not find the original conversation insofar (Discord does not allow to search through private channels).
I will try to find it over time.

**Comment by siliconwitch** [comment]
Closing. Can reopen if it pops up again
