### ISSUE TITLE
[feature request] Add in-app get-started guide

### ISSUE THREAD

**Issue by josuah** [brilliantlabsAR/noa-flutter#118]
The Frame device requires an extra step to get started using it, and if starting from the Noa application, it can be confusing to understand what the next step is. This can be fixed by a link from the application to the doc, or "get started" video.

Reported through YouTube
https://www.youtube.com/watch?v=Ls2AH25fIfc

**Comment by josuah** [comment]
The link to the doc could be this one:
https://docs.brilliant.xyz/frame/frame/#how-do-i-connect-to-my-frame-for-the-first-time

The link to the video could be this one:
https://www.youtube.com/watch?v=mOoaD1hvi5c

**Comment by siliconwitch** [comment]
video link added to app
