### ISSUE TITLE
[feature request] Display a picture of what was just taken

### ISSUE THREAD

**Issue by josuah** [brilliantlabsAR/noa-flutter#122]
To help users troubleshoot their use of the device, one suggestion to improve usability by email is:

> It would show the image in app or in frame and say something like "I'm sorry I don't see a lemon in [this] picture."
> As an end user, I might realize something was obstructing the view, my head wasn't oriented well, or it was blurred, so I need to be more still.

**Comment by josuah** [comment]
Also requested here:
https://discord.com/channels/963222352534048818/1247879507785023569

**Comment by josuah** [comment]
One suggested UI was to have a "tap 3 times" for saving the picture.
https://discord.com/channels/963222352534048818/984966420603482182/1248748258700951562

**Comment by siliconwitch** [comment]
Potential privacy issue so this is not planned
