### ISSUE TITLE
[feature request] Add "options" to see details about the query

### ISSUE THREAD

**Issue by josuah** [brilliantlabsAR/noa-flutter#123]
For users who work a lot with GPT, it can be useful to see details about each query, ~~for instance visible after a long~~ [on the hack tab] press on a past message:

- ~~Date/time.~~
- ~~The location used when asking.~~
- ~~The back-end that was selected for providing the answers~~
- The original audio
- The original camera image
- ~~The prompt parameters (temperature, etc)~~
- The time the query took on the server (for troubleshooting perforance: "why is it slow today?" -> network? -> noa? -> OpenAI?)

The items striked through are already present on the debug logs ("Hack" tab)

**Comment by siliconwitch** [comment]
Image is available when running the app in debug mode. Not possible in release mode due to potential privacy issues
