### ISSUE TITLE
Open Bluetooth settings if device already paired and pairing info is wrong

### ISSUE THREAD

**Issue by uma-shankar-TE** [brilliantlabsAR/noa-flutter#141]
if Encryption Insufficient error is there , we can open bluetooth setting to guide deletion of pairing info

https://pub.dev/packages/app_settings

https://stackoverflow.com/questions/59033513/is-there-a-method-in-flutter-to-open-androids-and-ioss-built-in-bluetooth-me

`ElevatedButton(
        child: Text("Bluetooth"),
        onPressed: () {
          AppSettings.openBluetoothSettings();
        },
      )`

**Comment by siliconwitch** [comment]
Problem with this is that it would jump to bluetooth settings for both incorrect phone bond, but also frame bond when it needs a pin reset. Better to just describe in the app directly how to unpair with an animation or something like that
