### ISSUE TITLE
[feature request] customize the AI parameters from the app

### ISSUE THREAD

**Issue by josuah** [brilliantlabsAR/noa-flutter#84]
Some inbound requests from users suggest to enable a few custom fields:

- API endpoint (and if needed, API key)
- AI temperature
- GPT version
- Pre-prompt

**Comment by siliconwitch** [comment]
All of these are already supported :) 

Except for changing of API endpoint. Apple doesn't let us do this because it's a way of getting around their in-app payments. Currently, we're using GPT-4o so if that stays then it's already the best option enabled by default for all users

**Comment by josuah** [comment]
For the record, it is also possible to set a "pre prompt" by simply speaking the instructions out loud.
![2024-06-08-141414_588x244_scrot](https://github.com/brilliantlabsAR/noa-flutter/assets/55351021/ed791a9b-1700-468d-8c99-a4411c02ede0)
