### ISSUE TITLE
[feature request] chinese, japanese, korean, [...] rendering as image

### ISSUE THREAD

**Issue by josuah** [brilliantlabsAR/noa-flutter#93]
Without requiring to modify the firmware, it is possible to render text as an image to support as much font as the app supports:
https://pub.dev/packages/widgets_to_image

This would enable arbitrary characters of any languages on Frame.

Feature requested by email.

**Comment by josuah** [comment]
An alternative is to update the font just before sending `display.text()`: refreshing the missing characters would allow all text to be displayed by loading only the minimum characters needed for rendering a paragraph.

**Comment by josuah** [comment]
An alternative is to have a drop-down to select a few alternative fonts, which would work for i.e. Cyrillic or Greek or other character sets without combining characters, right-to-left, or too many characters.

**Comment by josuah** [comment]
Requested today by email for Japanese / Chinese

**Comment by josuah** [comment]
Requested today by email for Chinese

**Comment by josuah** [comment]
Connected to https://github.com/brilliantlabsAR/frame-codebase/issues/169

**Comment by siliconwitch** [comment]
None of these are planned currently, but worth keeping a tally of most requested languages
